
_target_: src.world_models.iris_world_model.networks.tokenizer.tokenizer.Tokenizer
vocab_size: 512
embed_dim: 512
encoder:
  _target_: src.world_models.iris_world_model.networks.tokenizer.nets.Encoder
  config:
    _target_: src.world_models.iris_world_model.networks.tokenizer.nets.EncoderDecoderConfig
    resolution: 64
    in_channels: 3
    z_channels: 512
    ch: 64
    ch_mult: [1, 1, 1, 1, 1] # changed from [1, 1, 1, 1, 1]
    num_res_blocks: 2
    attn_resolutions: [8, 16]
    out_ch: 3
    dropout: 0.0
decoder:
  _target_: src.world_models.iris_world_model.networks.tokenizer.nets.Decoder
  config: ${..encoder.config}