_target_: src.world_models.iris_world_model.networks.transformer.TransformerConfig
tokens_per_block: 17 #changed from: 17
max_blocks: 20 # changed from: 20 (tokens_per_block * max_blocks = 340)
attention: 'causal'
num_layers: 10
num_heads: 4
embed_dim: 256
embed_pdrop: 0.1
resid_pdrop: 0.1
attn_pdrop: 0.1
